[workspace]
resolver = "2"
members = [
    "crates/codpiece-gguf",
    "crates/codpiece-ggml-sys",
    "crates/codpiece-tok",
    "crates/codpiece-sample",
    "crates/codpiece-model",
    "crates/codpiece-vision",
    "crates/codpiece-server",
    "crates/codpiece-cli",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"

[profile.release]
lto = "thin"
codegen-units = 1
